RSI = 14
BULL_RSI = 7
BULL_RSI_high = 82
BULL_RSI_low = 60
BEAR_RSI = 14
BEAR_RSI_high = 60
BEAR_RSI_low = 15
BULL_MOD_high = 5
BULL_MOD_low = -5
BEAR_MOD_high = 15
BEAR_MOD_low = -5
ADX = 14
ADX_high = 70
ADX_low = 50
PINGPONG_GAINS_PERCENTAGE = 10
SMA_long = 10
SMA_short = 21
DEMA_long = 10
DEMA_short = 21
Stop_Loss_Percent = 3
Stop_Gain_Percent = 3
Min_Loss_Percent = 1.5
Min_Gain_Percent = 1.5
