# This file is a part of configuration , default setup enable sqlite adapter
#and need sqlite3 as dependencies for work.

enabled = true
debug = true
adapter = "sqlite"
[dependencies]
module="sqlite3"

[watch]
exchange = ""
currency = ""
asset = ""
key=""
secret=""

