# This file is a part of configuration , default setup enable sqlite adapter
#and need sqlite3 as dependencies for work.

enabled = true
debug = true
adapter = "sqlite"
[[dependencies]]
module="sqlite3"

#Watch Exchange Market :BTC-LTC

[[watch]]
exchange = "bitfinex"
currency = "BTC"
asset = "LTC"
key=""
secret=""
[[watch]]
exchange = "kraken"
currency = "XBT"
asset = "LTC"
key=""
secret=""
[[watch]]
exchange = "poloniex"
currency = "BTC"
asset = "LTC"
key=""
secret=""
